# Databricks notebook source
import pandas as pd

# COMMAND ----------

#Load the data
df=spark.table('data_agent.data.bright_coffee').toPandas()
df.head()


# COMMAND ----------

# checking statistics in transaction_qty column
df[['transaction_qty']].describe()

# COMMAND ----------

# Checking columns in the dataset
df.columns

# COMMAND ----------

# Checking for null values
df.isnull().sum()

# COMMAND ----------

# Checking the Data Types
df.dtypes

# COMMAND ----------

#Convert both columns to numeric 
df["transaction_qty"] = pd.to_numeric(df["transaction_qty"], errors="coerce")
df["unit_price"] = pd.to_numeric(df["unit_price"], errors="coerce")

# COMMAND ----------

# Create a Revenue column using unit_price and transaction_qty
df['revenue']=df['unit_price']*df['transaction_qty']
df.head()

# COMMAND ----------

df.describe() 

# COMMAND ----------

# checking the unique stores in the data
df['store_location'].unique()

# COMMAND ----------

# Checking the unique product categories
df['product_category'].unique()

# COMMAND ----------

# MAGIC %md
# MAGIC ###  Validating My Coffee Sales Analytics Agent's Answers-Using Code

# COMMAND ----------

# MAGIC %md
# MAGIC **Question 1**:
# MAGIC - What is the total revenue generated by Bright Coffee during the entire period covered by the dataset?

# COMMAND ----------

df['revenue'].sum()


# COMMAND ----------

# MAGIC %md     
# MAGIC **Question 2**:
# MAGIC - Which product category generated the highest total sales revenue, and what percentage of overall revenue did it contribute?

# COMMAND ----------


# Total revenue by product category
category_revenue = (
    df.groupby("product_category")["revenue"]
      .sum()
      .reset_index()
)

# Sort from highest to lowest revenue
category_revenue = category_revenue.sort_values(by="revenue", ascending=False)

# Overall revenue
total_revenue = category_revenue["revenue"].sum()

# Calculate percentage contribution
category_revenue["percentage_contribution"] = (
    category_revenue["revenue"] / total_revenue * 100
).round(2)

# Display all categories
print(category_revenue)

# Display the top category
top_category = category_revenue.iloc[0]

print("\nHighest Revenue Category")
print(f"Category: {top_category['product_category']}")
print(f"Revenue: {top_category['revenue']:.2f}")
print(f"Percentage of Total Revenue: {top_category['percentage_contribution']:.2f}%")

# COMMAND ----------

# MAGIC %md
# MAGIC **Question 3**:
# MAGIC - Which store location had the highest sales revenue, and how does it compare with the lowest-performing store

# COMMAND ----------

# Ensure revenue is numeric
df["revenue"] = pd.to_numeric(df["revenue"], errors="coerce")

# Calculate total revenue by store
store_revenue = (
    df.groupby("store_location")["revenue"]
      .sum()
      .reset_index()
      .sort_values(by="revenue", ascending=False)
)

# Highest-performing store
highest_store = store_revenue.iloc[0]

# Lowest-performing store
lowest_store = store_revenue.iloc[-1]

# Calculate the difference
revenue_difference = highest_store["revenue"] - lowest_store["revenue"]

# Calculate percentage difference
percentage_difference = (
    (revenue_difference / lowest_store["revenue"]) * 100
)

# Display all store revenues
print(store_revenue)

print("\nHighest-Performing Store")
print(f"Store: {highest_store['store_location']}")
print(f"Revenue: {highest_store['revenue']:.2f}")

print("\nLowest-Performing Store")
print(f"Store: {lowest_store['store_location']}")
print(f"Revenue: {lowest_store['revenue']:.2f}")

print(f"\nRevenue Difference: {revenue_difference:.2f}")
print(f"Percentage Difference: {percentage_difference:.2f}%")

# COMMAND ----------

# MAGIC %md
# MAGIC ### Validating My Coffee Sales Analytics Agent's Answers-Using Visuals

# COMMAND ----------

import matplotlib.pyplot as plt

# COMMAND ----------

# MAGIC %md
# MAGIC **Question 2**:
# MAGIC - Which product category generated the highest total sales revenue

# COMMAND ----------

category_revenue = df.groupby("product_category")["revenue"].sum().sort_values(ascending=False)
category_revenue.plot(kind="bar")

plt.title("Revenue by Product Category")
plt.xlabel("Product Category")
plt.ylabel("Revenue")
plt.show()

# COMMAND ----------

# MAGIC %md
# MAGIC **Question 3**:
# MAGIC - Which store location had the highest sales revenue

# COMMAND ----------

store_revenue = df.groupby("store_location")["revenue"].sum().sort_values(ascending=False)
store_revenue.plot(kind="bar")

plt.title("Revenue by Store Location")
plt.xlabel("Store Location")
plt.ylabel("Revenue")
plt.show()